# Project information
site_name: 'UpdateHub'
site_description: 'All your devices, always updated'

# Copyright
copyright: 'Copyright &copy; 2022 O.S. Systems'

# Repository
repo_name: 'UpdateHub/updatehub.github.io'
repo_url: 'https://github.com/UpdateHub/updatehub.github.io'

# Deployment
remote_branch: master

# Configuration
theme:
  name: 'material'
  language: 'en'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'img/assets/favicon.ico'
  features:
    - navigation.tabs

extra_css:
  - 'stylesheets/extra.css'

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: 'fontawesome/brands/gitter'
      link: 'https://gitter.im/UpdateHub'
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/OSSystems'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/OSSystemsNews?s=20'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/ossystems'

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_ID"]
  - auto

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# Navigation
nav:
  - Introduction: index.md
  - What is UpdateHub: what-is-updatehub.md
  - Quick starting with Raspberry Pi 3: quick-starting-with-raspberrypi3.md
  - Using UpdateHub Cloud: 
    - UpdateHub Cloud dashboard: updatehub-cloud/dashboard.md
    - Managing a Product: updatehub-cloud/product.md
    - Handling a Device: updatehub-cloud/device.md
    - Package and Rollout: updatehub-cloud/package-rollout.md
    - Your menu account: updatehub-cloud/menu.md
  - Handling UpdateHub agent:
    - Meeting the UpdateHub Agent: updatehub-agent/intro.md
    - The State Machine and the Flows: updatehub-agent/state-machine.md
    - Controlling the Agent: updatehub-agent/controlling-agent.md
  - Integrating with Yocto Project:
    - Supported machines: yocto-project/supported-machines.md
    - Yocto Project guide: yocto-project/yocto-project-guide.md
    - Yocto Project reference: yocto-project/yocto-project-reference.md
    - Glossary of variables: yocto-project/glossary.md
  - Integrating with Zephyr Project:
    - Zephyr Project guide: zephyr-project/zephyr-project-guide.md
  - FAQ: faq/faq-questions.md

